# The interval (in seconds) between broadcasts
interval: 1800

# The message template for broadcasting player coordinates
# Available placeholders:
# - <player>: The name of the selected random player
# - <x>, <y>, <z>: The coordinates of the player's location
message: "<#dc143c><player> is currently at <x>, <y>, <z>."
